#!/usr/bin/env node

/**
 * Supabase SQL Executor - Exécute le script SQL via l'API Supabase
 * Usage: node execute-sql.js
 */

require('dotenv').config();

const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    console.error('❌ Erreur: Variables manquantes dans .env.local');
    console.error('Assurez-vous que SUPABASE_URL et SUPABASE_SERVICE_ROLE_KEY sont définis\n');
    process.exit(1);
}

const sqlScript = `
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tech TEXT[] DEFAULT '{}',
  github TEXT,
  live TEXT,
  featured BOOLEAN DEFAULT false,
  archived BOOLEAN DEFAULT false
);

-- Certifications Table
CREATE TABLE IF NOT EXISTS certifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  issuer TEXT NOT NULL,
  year INTEGER NOT NULL,
  description TEXT NOT NULL,
  url TEXT,
  archived BOOLEAN DEFAULT false
);

-- Education Table
CREATE TABLE IF NOT EXISTS education (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  institution TEXT NOT NULL,
  start_year INTEGER NOT NULL,
  end_year TEXT,
  description TEXT NOT NULL,
  archived BOOLEAN DEFAULT false
);

-- CVs Table
CREATE TABLE IF NOT EXISTS cvs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  filename TEXT NOT NULL,
  size INTEGER NOT NULL,
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  content_type TEXT NOT NULL,
  base64 TEXT NOT NULL,
  active BOOLEAN DEFAULT false
);

-- Testimonials Table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  author TEXT NOT NULL,
  text TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  archived BOOLEAN DEFAULT false
);

-- Analytics Table
CREATE TABLE IF NOT EXISTS analytics (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  page_views INTEGER DEFAULT 0,
  cv_downloads INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  session_duration TEXT DEFAULT '0m 0s',
  monthly_activity JSONB DEFAULT '[]'::jsonb,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
-- Projects
CREATE POLICY IF NOT EXISTS "Projects are publicly readable" ON projects FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert projects" ON projects FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update projects" ON projects FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete projects" ON projects FOR DELETE USING (auth.role() = 'authenticated');

-- Certifications
CREATE POLICY IF NOT EXISTS "Certifications are publicly readable" ON certifications FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert certifications" ON certifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update certifications" ON certifications FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete certifications" ON certifications FOR DELETE USING (auth.role() = 'authenticated');

-- Education
CREATE POLICY IF NOT EXISTS "Education is publicly readable" ON education FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert education" ON education FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update education" ON education FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete education" ON education FOR DELETE USING (auth.role() = 'authenticated');

-- CVs
CREATE POLICY IF NOT EXISTS "CVs are publicly readable" ON cvs FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert cvs" ON cvs FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update cvs" ON cvs FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete cvs" ON cvs FOR DELETE USING (auth.role() = 'authenticated');

-- Testimonials
CREATE POLICY IF NOT EXISTS "Testimonials are publicly readable" ON testimonials FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert testimonials" ON testimonials FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update testimonials" ON testimonials FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete testimonials" ON testimonials FOR DELETE USING (auth.role() = 'authenticated');

-- Analytics
CREATE POLICY IF NOT EXISTS "Analytics are publicly readable" ON analytics FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can update analytics" ON analytics FOR UPDATE USING (auth.role() = 'authenticated');
`;

async function executeSQL() {
    console.log('🚀 Exécution du script SQL...\n');
    console.log('📍 URL:', SUPABASE_URL);
    console.log('🔑 Service Role Key: Utilisée\n');
    
    try {
        // L'API REST de Supabase ne supporte pas directement l'exécution de SQL arbitraire
        // On va afficher le SQL à copier-coller dans le dashboard
        
        console.log('⚠️  Note: L\'API REST de Supabase ne supporte pas l\'exécution de SQL arbitraire');
        console.log('Pour créer les tables, utilise le SQL Editor du dashboard:\n');
        
        console.log('='.repeat(70));
        console.log('INSTRUCTIONS - 3 ÉTAPES:');
        console.log('='.repeat(70));
        console.log('\n1. Va à: https://app.supabase.com/projects');
        console.log('2. Ouvre le projet "porto-database"');
        console.log('3. Clique "SQL Editor" (à gauche du menu)\n');
        
        console.log('4. Clique "New Query"');
        console.log('5. Copie TOUT le texte ci-dessous');
        console.log('6. Colle-le dans l\'éditeur SQL');
        console.log('7. Clique "RUN" ou presse Ctrl+Enter\n');
        
        console.log('='.repeat(70));
        console.log('SCRIPT SQL À EXÉCUTER:');
        console.log('='.repeat(70));
        console.log(sqlScript);
        console.log('='.repeat(70) + '\n');
        
        console.log('✅ Une fois exécuté avec succès, tu verras "Success" dans Supabase');
        console.log('📊 Puis je vais intégrer Supabase au dashboard!\n');
        
    } catch (error) {
        console.error('❌ Erreur:', error.message);
        process.exit(1);
    }
}

// Alternative: Utiliser curl si disponible
function showCurlAlternative() {
    console.log('\n\n='.repeat(70));
    console.log('ALTERNATIVE - Via cURL (si installé):');
    console.log('='.repeat(70));
    console.log('\nCopie et exécute cette commande dans le terminal:\n');
    
    const curlCmd = `curl -X POST \\
  "${SUPABASE_URL}/rest/v1/sql" \\
  -H "Authorization: Bearer ${SERVICE_ROLE_KEY}" \\
  -H "Content-Type: application/json" \\
  -d '{"query":"CREATE TABLE IF NOT EXISTS projects ..."}'\n`;
    
    console.log('(Cette méthode est limitée pour les gros scripts)\n');
}

executeSQL().catch(error => {
    console.error('Erreur:', error);
    process.exit(1);
});
