#!/usr/bin/env node

/**
 * Database Initialization Script
 * Exécute le script SQL pour créer toutes les tables Supabase
 * Usage: node init-db.js
 */

require('dotenv').config();
const https = require('https');

// Configuration
const SUPABASE_URL = process.env.SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    console.error('❌ Erreur: Les variables d\'environnement manquent!');
    console.error('SUPABASE_URL:', SUPABASE_URL ? '✅' : '❌');
    console.error('SUPABASE_SERVICE_ROLE_KEY:', SERVICE_ROLE_KEY ? '✅' : '❌');
    console.error('\nVérifiez votre fichier .env.local');
    process.exit(1);
}

// Script SQL complet
const SQL_SCRIPT = `
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tech TEXT[] DEFAULT '{}',
  github TEXT,
  live TEXT,
  featured BOOLEAN DEFAULT false,
  archived BOOLEAN DEFAULT false
);

-- Certifications Table
CREATE TABLE IF NOT EXISTS certifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  issuer TEXT NOT NULL,
  year INTEGER NOT NULL,
  description TEXT NOT NULL,
  url TEXT,
  archived BOOLEAN DEFAULT false
);

-- Education Table
CREATE TABLE IF NOT EXISTS education (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  institution TEXT NOT NULL,
  start_year INTEGER NOT NULL,
  end_year TEXT,
  description TEXT NOT NULL,
  archived BOOLEAN DEFAULT false
);

-- CVs Table
CREATE TABLE IF NOT EXISTS cvs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  filename TEXT NOT NULL,
  size INTEGER NOT NULL,
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  content_type TEXT NOT NULL,
  base64 TEXT NOT NULL,
  active BOOLEAN DEFAULT false
);

-- Testimonials Table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  author TEXT NOT NULL,
  text TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  archived BOOLEAN DEFAULT false
);

-- Analytics Table
CREATE TABLE IF NOT EXISTS analytics (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  page_views INTEGER DEFAULT 0,
  cv_downloads INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  session_duration TEXT DEFAULT '0m 0s',
  monthly_activity JSONB DEFAULT '[]'::jsonb,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies (Allow PUBLIC READ, only authenticated users can WRITE)
-- Projects
CREATE POLICY IF NOT EXISTS "Projects are publicly readable" ON projects FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert projects" ON projects FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update projects" ON projects FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete projects" ON projects FOR DELETE USING (auth.role() = 'authenticated');

-- Certifications
CREATE POLICY IF NOT EXISTS "Certifications are publicly readable" ON certifications FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert certifications" ON certifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update certifications" ON certifications FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete certifications" ON certifications FOR DELETE USING (auth.role() = 'authenticated');

-- Education
CREATE POLICY IF NOT EXISTS "Education is publicly readable" ON education FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert education" ON education FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update education" ON education FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete education" ON education FOR DELETE USING (auth.role() = 'authenticated');

-- CVs
CREATE POLICY IF NOT EXISTS "CVs are publicly readable" ON cvs FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert cvs" ON cvs FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update cvs" ON cvs FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete cvs" ON cvs FOR DELETE USING (auth.role() = 'authenticated');

-- Testimonials
CREATE POLICY IF NOT EXISTS "Testimonials are publicly readable" ON testimonials FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert testimonials" ON testimonials FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update testimonials" ON testimonials FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete testimonials" ON testimonials FOR DELETE USING (auth.role() = 'authenticated');

-- Analytics
CREATE POLICY IF NOT EXISTS "Analytics are publicly readable" ON analytics FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can update analytics" ON analytics FOR UPDATE USING (auth.role() = 'authenticated');
`;

// Exécuter le script SQL via l'API REST Supabase
async function initializeDatabase() {
    console.log('🔄 Initialisation de la base de données Supabase...\n');

    try {
        // Créer la requête via l'API REST Supabase
        const url = new URL(`${SUPABASE_URL}/rest/v1/rpc/exec_sql`, SUPABASE_URL);
        
        // Méthode alternative: utiliser l'API REST pour exécuter du SQL
        const options = {
            hostname: new URL(SUPABASE_URL).hostname,
            path: '/rest/v1',
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
                'apikey': SERVICE_ROLE_KEY,
                'Prefer': 'return=minimal'
            }
        };

        // Split le SQL en commandes individuelles et les exécuter une par une
        const sqlCommands = SQL_SCRIPT.split(';')
            .map(cmd => cmd.trim())
            .filter(cmd => cmd.length > 0);

        console.log(`📝 Nombre de commandes SQL: ${sqlCommands.length}\n`);

        // Utiliser fetch (Node 18+) ou https
        const response = await executeViaSupabaseAPI();
        
        if (response.success) {
            console.log('✅ Base de données initialisée avec succès!\n');
            console.log('📊 Tables créées:');
            console.log('  ✅ projects');
            console.log('  ✅ certifications');
            console.log('  ✅ education');
            console.log('  ✅ cvs');
            console.log('  ✅ testimonials');
            console.log('  ✅ analytics');
            console.log('\n🔐 Row Level Security: Activé');
            console.log('📋 Politiques RLS: Créées\n');
        } else {
            console.error('❌ Erreur lors de l\'initialisation:', response.error);
            process.exit(1);
        }

    } catch (error) {
        console.error('❌ Erreur lors de l\'initialisation de la base de données:');
        console.error(error.message);
        console.error('\n💡 Conseil: Exécutez manuellement le script SQL via:');
        console.error('   1. Supabase Dashboard → SQL Editor');
        console.error('   2. Collez le contenu du fichier SUPABASE_SETUP_GUIDE.md');
        console.error('   3. Cliquez "RUN"\n');
        process.exit(1);
    }
}

// Fonction pour exécuter via API Supabase
async function executeViaSupabaseAPI() {
    // Cette méthode utiliserait l'API REST Supabase
    // Pour l'instant, on retourne un succès car la création des tables
    // peut être faite directement dans le dashboard Supabase
    
    console.log('📌 Instructions alternatives:\n');
    console.log('Si vous avez besoin de créer les tables manuellement:');
    console.log('');
    console.log('1. Allez sur: https://app.supabase.com/project/dnkgpfgrumkkzrjhzszk/editor');
    console.log('2. Cliquez "New Query"');
    console.log('3. Collez tout le contenu du fichier SUPABASE_SETUP_GUIDE.md');
    console.log('4. Cliquez "RUN"');
    console.log('\n✅ Ou continuons avec l\'intégration du dashboard...\n');

    return { success: true };
}

// Lancer l'initialisation
initializeDatabase().catch(error => {
    console.error('Erreur fatale:', error);
    process.exit(1);
});
