#!/usr/bin/env node

/**
 * Simple SQL Display Script - Pas de dépendances
 */

const fs = require('fs');
const path = require('path');

// Lire le fichier .env.local manuellement
const envFile = path.join(__dirname, '.env.local');
let envVars = {};

if (fs.existsSync(envFile)) {
    const content = fs.readFileSync(envFile, 'utf-8');
    content.split('\n').forEach(line => {
        const [key, ...value] = line.split('=');
        if (key && key.trim()) {
            envVars[key.trim()] = value.join('=').trim();
        }
    });
}

const SUPABASE_URL = envVars.SUPABASE_URL;
const SERVICE_ROLE_KEY = envVars.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    console.error('❌ Variables manquantes dans .env.local');
    process.exit(1);
}

const sqlScript = `
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Projects Table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tech TEXT[] DEFAULT '{}',
  github TEXT,
  live TEXT,
  featured BOOLEAN DEFAULT false,
  archived BOOLEAN DEFAULT false
);

-- Certifications Table
CREATE TABLE IF NOT EXISTS certifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  issuer TEXT NOT NULL,
  year INTEGER NOT NULL,
  description TEXT NOT NULL,
  url TEXT,
  archived BOOLEAN DEFAULT false
);

-- Education Table
CREATE TABLE IF NOT EXISTS education (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  title TEXT NOT NULL,
  institution TEXT NOT NULL,
  start_year INTEGER NOT NULL,
  end_year TEXT,
  description TEXT NOT NULL,
  archived BOOLEAN DEFAULT false
);

-- CVs Table
CREATE TABLE IF NOT EXISTS cvs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  filename TEXT NOT NULL,
  size INTEGER NOT NULL,
  upload_date TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  content_type TEXT NOT NULL,
  base64 TEXT NOT NULL,
  active BOOLEAN DEFAULT false
);

-- Testimonials Table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  author TEXT NOT NULL,
  text TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  archived BOOLEAN DEFAULT false
);

-- Analytics Table
CREATE TABLE IF NOT EXISTS analytics (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
  page_views INTEGER DEFAULT 0,
  cv_downloads INTEGER DEFAULT 0,
  unique_visitors INTEGER DEFAULT 0,
  session_duration TEXT DEFAULT '0m 0s',
  monthly_activity JSONB DEFAULT '[]'::jsonb,
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE education ENABLE ROW LEVEL SECURITY;
ALTER TABLE cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE analytics ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
-- Projects
CREATE POLICY IF NOT EXISTS "Projects are publicly readable" ON projects FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert projects" ON projects FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update projects" ON projects FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete projects" ON projects FOR DELETE USING (auth.role() = 'authenticated');

-- Certifications
CREATE POLICY IF NOT EXISTS "Certifications are publicly readable" ON certifications FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert certifications" ON certifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update certifications" ON certifications FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete certifications" ON certifications FOR DELETE USING (auth.role() = 'authenticated');

-- Education
CREATE POLICY IF NOT EXISTS "Education is publicly readable" ON education FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert education" ON education FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update education" ON education FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete education" ON education FOR DELETE USING (auth.role() = 'authenticated');

-- CVs
CREATE POLICY IF NOT EXISTS "CVs are publicly readable" ON cvs FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert cvs" ON cvs FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update cvs" ON cvs FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete cvs" ON cvs FOR DELETE USING (auth.role() = 'authenticated');

-- Testimonials
CREATE POLICY IF NOT EXISTS "Testimonials are publicly readable" ON testimonials FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can insert testimonials" ON testimonials FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can update testimonials" ON testimonials FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY IF NOT EXISTS "Authenticated users can delete testimonials" ON testimonials FOR DELETE USING (auth.role() = 'authenticated');

-- Analytics
CREATE POLICY IF NOT EXISTS "Analytics are publicly readable" ON analytics FOR SELECT USING (true);
CREATE POLICY IF NOT EXISTS "Authenticated users can update analytics" ON analytics FOR UPDATE USING (auth.role() = 'authenticated');
`;

console.log('\n🚀 SUPABASE DATABASE INITIALIZATION\n');
console.log('='.repeat(70));
console.log('📋 Configuration Détectée:');
console.log('='.repeat(70));
console.log(`URL: ${SUPABASE_URL}`);
console.log(`Service Role Key: ${SERVICE_ROLE_KEY.substring(0, 30)}...`);
console.log('\n');

console.log('📌 ÉTAPES POUR CRÉER LES TABLES:\n');
console.log('1️⃣  Va à: https://app.supabase.com/projects');
console.log('2️⃣  Ouvre le projet');
console.log('3️⃣  Clique "SQL Editor" (gauche du menu)');
console.log('4️⃣  Clique "New Query"');
console.log('5️⃣  Copie TOUT le SQL ci-dessous');
console.log('6️⃣  Colle dans l\'éditeur');
console.log('7️⃣  Clique "RUN" (ou Ctrl+Enter)\n');

console.log('='.repeat(70));
console.log('📝 SCRIPT SQL À EXÉCUTER:');
console.log('='.repeat(70));
console.log('\n');
console.log(sqlScript);
console.log('\n' + '='.repeat(70));
console.log('✅ FIN DU SCRIPT');
console.log('='.repeat(70));
console.log('\n💡 Après exécution, les 6 tables seront créées avec:');
console.log('   ✅ Timestamps automatiques');
console.log('   ✅ Row Level Security (RLS)');
console.log('   ✅ Politiques publiques lecture/authentifiée écriture\n');

console.log('👉 Une fois complété, dis-moi et je vais:');
console.log('   • Intégrer Supabase au dashboard');
console.log('   • Remplacer localStorage par Supabase');
console.log('   • Tester la synchronisation\n');
